/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: b39ab39b4852f25c61ee3fe17cd510b2)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
		durableNamespaces: "Chat";
	}
	interface Env {
		GROQ_API_KEY: string;
		GOOGLE_GENERATIVE_AI_API_KEY: string;
		Chat: DurableObjectNamespace<import("./src/server").Chat>;
		DB: D1Database;
		AI: Ai;
		KNOWLEDGE_GRAPH_WORKFLOW: Workflow;
		QUERY_GRAPH_WORKFLOW: Workflow;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "GROQ_API_KEY" | "GOOGLE_GENERATIVE_AI_API_KEY">> {}
}
